
let filas = [
			[["A1","Disponible"],["A2","Disponible"],["A3","Disponible"],
				  ["A4","Disponible"],["A5","Disponible"],["A6","Disponible"],
				  ["A7","Ocupado"],["A8","Ocupado"],["A9","Ocupado"],
				  ["A10","Ocupado"]],
            [["B1","Disponible"],["B2","Disponible"],["B3","Disponible"],
				  ["B4","Disponible"],["B5","Disponible"],["B6","Disponible"],
				  ["B7","Disponible"],["B8","Ocupado"],["B9","Ocupado"],
				  ["B10","Ocupado"]],
            [["C1","Disponible"],["C2","Disponible"],["C3","Ocupado"],
				  ["C4","Ocupado"],["C5","Disponible"],["C6","Disponible"],
				  ["C7","Disponible"],["C8","Disponible"],["C9","Disponible"],
				  ["C10","Disponible"]],
            [["D1","Ocupado"],["D2","Ocupado"],["D3","Ocupado"],
				  ["D4","Ocupado"],["D5","Ocupado"],["D6","Ocupado"],
				  ["D7","Disponible"],["D8","Disponible"],["D9","Disponible"],
				  ["D10","Disponible"]],
            [["E1","Disponible"],["E2","Disponible"],["E3","Disponible"],
				  ["E4","Disponible"],["E5","Disponible"],["E6","Disponible"],
				  ["E7","Ocupado"],["E8","Ocupado"],["E9","Ocupado"],
				  ["E10","Disponible"]],
            [["F1","Disponible"],["F2","Disponible"],["F3","Disponible"],
				  ["F4","Disponible"],["F5","Disponible"],["F6","Disponible"],
				  ["F7","Disponible"],["F8","Disponible"],["F9","Disponible"],
				  ["F10","Disponible"]],
            [["G1","Disponible"],["G2","Disponible"],["G3","Ocupado"],
				  ["G4","Ocupado"],["G5","Ocupado"],["G6","Ocupado"],
				  ["G7","Disponible"],["G8","Disponible"],["G9","Disponible"],
				  ["G10","Disponible"]];

let asientos_seleccionados=[];